import Head from 'next/head';
import { Manrope } from 'next/font/google';
import Link from 'next/link';

const manrope = Manrope({ subsets: ['latin'] });

function NextHead() {
  return (
    <Head>
      <title>Thunkworks</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/images/favicon.ico" />
    </Head>
  );
}

const coreLinks = [
  {
    label: 'Text',
    href: 'core/Text/',
  },
  {
    label: 'Title',
    href: 'core/Title/',
  },
  {
    label: 'Group',
    href: 'core/Group/',
  },
  {
    label: 'Radio',
    href: 'core/Radio/',
  },
  {
    label: 'Button',
    href: 'core/Button/',
  },
  {
    label: 'Checkbox',
    href: 'core/Checkbox/',
  },
];

export default function Home() {
  return (
    <>
      <NextHead />
      <main className={manrope.className}>
        <h1>Home</h1>

        {coreLinks.map((item) => (
          <li key={item.href}>
            <Link href={item.href}>{item.label}</Link>
          </li>
        ))}
      </main>
    </>
  );
}
