import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { Button } from '@thunkworks/core';
import { Manrope } from 'next/font/google';

const manrope = Manrope({ subsets: ['latin'] });

function NextHead() {
  return (
    <Head>
      <title>Thunkworks</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/images/favicon.ico" />
    </Head>
  );
}

export default function Home() {
  return (
    <React.Fragment>
      <NextHead />
      <main className={manrope.className}>
        <h1>Home</h1>
        <Button>Button</Button>
      </main>
    </React.Fragment>
  );
}
